platform :ios, '10.0'

target 'template' do
  pod 'MPIOSRuntime', :git => 'https://github.com/mpflutter/mp_ios_runtime.git', :branch => '0.7.1'
  pod 'SDWebImage', '~> 5.11'
  pod 'SDWebImageSVGKitPlugin'
  pod 'SVGKit', '< 3.0.0'
end
